spring.application.name=recipejson
spring.datasource.url=jdbc:mysql://localhost:3306/recipedb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Yazhini22@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.batch_size=50
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

